name: 'Lighthouse PR Commenter for Vercel'
description: 'Runs Lighthouse audits against a Vercel preview deployment and posts results as a GitHub PR comment.'
author: 'Robbie Crenshaw'
branding:
  icon: 'zap'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token to authenticate requests and post PR comments'
    required: true
  max_timeout:
    description: 'Maximum time (in seconds) to wait for the Vercel deployment to become available'
    required: false
    default: '180'
  check_interval:
    description: 'Time (in seconds) between deployment availability checks'
    required: false
    default: '10'
    
runs:
  using: 'node20'
  main: 'dist/index.js'
